### ISSUE TITLE
Offset Slider

### ISSUE THREAD

**Issue by tlwoods07** [maginative/relayedu-styleguide#1]
Created an offset slider on the About Relay & History page (https://master-7rqtwti-at3ucti75d2e6.us-2.platformsh.site/about-relay-history). Added three slides. The module becomes uneditable in the layout view and the images and text do not display when the page is viewed. "Learn about our..." is the title text in the module.

![Screen Shot 2020-12-19 at 3 45 33 PM](https://user-images.githubusercontent.com/75328077/102699266-76cdad00-4211-11eb-8fba-acf51b44869a.png)

**Comment by cmcky** [comment]
@tlwoods07 moving this to the Drupal 9 project.
